name: Fly Deploy
on: [push]

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create token file
        run: |
          touch token
          echo -e "${{secrets.BOT_TOKEN}}" >> token

      - name: Setup flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master
    
      - name: Deploy
        run: flyctl deploy --remote-only --detach
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}